/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appcoffee;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class frmEditUser extends javax.swing.JFrame {

    public String User; // tên user
    public String Chucvu; // lưu chức vụ
    public String Tenhienthi; // lưu tên hiển thị
    connectSql cntSql;
    ResultSet rs; // lưu dữ liệu đọc từ SqlDataReader
    /**
     * Creates new form frmEditUser
     */
    
    public frmEditUser() { 
        initComponents();  
        String ur = "sa";
        String ps = "123";
        String u = "jdbc:sqlserver://localhost:1433;databaseName=QLCaPhe;encrypt=true;trustServerCertificate=true";
        cntSql = new connectSql(ur, ps, u);
        txtOldPassword.setEnabled(false);            
        txtNewPassword.setEnabled(false);
        txtAgainNewPassword.setEnabled(false);
    }
    
    public frmEditUser(String user, String chucvu, String tenhienthi) {
        initComponents();
                
        // hello
        String ur = "sa";
        String ps = "123456";
        String u = "jdbc:sqlserver://localhost:1433;databaseName=QLCaPhe;encrypt=true;trustServerCertificate=true";
        cntSql = new connectSql(ur, ps, u);
        
        this.User = user.replaceAll("\\s+", ""); // gán tên đăng nhập
        this.Chucvu = chucvu.replaceAll("\\s+", ""); // gán chức vụ
        this.Tenhienthi = tenhienthi.replaceAll("\\s+", ""); // gán tên hiển thị
        
        txtTenTK.setText(User);
        txtTenHT.setText(Tenhienthi);
        
        txtOldPassword.setEnabled(false);            
        txtNewPassword.setEnabled(false);
        txtAgainNewPassword.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        chkChangeMK = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnThayDoi = new javax.swing.JButton();
        txtTenTK = new javax.swing.JTextField();
        txtTenHT = new javax.swing.JTextField();
        txtOldPassword = new javax.swing.JTextField();
        txtNewPassword = new javax.swing.JTextField();
        txtAgainNewPassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Thông Tin Tài Khoản");

        jLabel2.setText("Tên tài khoản");

        jLabel3.setText("Tên hiển thị");

        jLabel4.setText("Thay đổi mật khẩu");

        chkChangeMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkChangeMKActionPerformed(evt);
            }
        });

        jLabel5.setText("Mật khẩu cũ");

        jLabel6.setText("Mật khẩu mới");

        jLabel7.setText("Nhập lại mật khẩu");

        btnThayDoi.setText("Thay Đổi");
        btnThayDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThayDoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenTK)
                            .addComponent(txtTenHT, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkChangeMK, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThayDoi)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtOldPassword)
                                .addComponent(txtNewPassword)
                                .addComponent(txtAgainNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtTenHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(chkChangeMK))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAgainNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnThayDoi)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThayDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThayDoiActionPerformed
        // TODO add your handling code here:
        if (!txtNewPassword.getText().equals(txtAgainNewPassword.getText())) // check nếu mật khẩu mới mà nhập lại mẫu khẩu không khớp thì thay đổi không thành cônc
        {
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu mới không khớp với nhau");
            return;
        }
        // cập nhật lại mật khẩu mới nếu đúng tài khoản và nhập đúng mật khẩu cũ
        //string sql = "Update TaiKhoan set matKhau = '" + txtmknew.Text + "' Where matKhau ='" + txtmkold.Text + "' AND tenDangNhap ='" + txttentk.Text + "'";
        //int kq = db.GetNonQuery(sql);
        else
        {
            String str = "SELECT matKhau FROM TaiKhoan WHERE tenDangNhap ='"+User.trim()+"'";
            try {
                rs = cntSql.getQuery(str);
                rs.next();
                String mk = rs.getString("matKhau").replaceAll("\\s+", "");
                if(mk.equals(txtOldPassword.getText()))
                {
                    str = "Update TaiKhoan set matKhau = '" + txtNewPassword.getText() + "' Where matKhau ='" + txtOldPassword.getText() + "' AND tenDangNhap ='" + User + "'";
                    cntSql.getUpdateQuery(str);
                    JOptionPane.showMessageDialog(rootPane, "Thay đổi thành công");
                    txtOldPassword.setText("");
                    txtNewPassword.setText("");
                    txtAgainNewPassword.setText("");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Mật khẩu cũ không đúng");
                }
            } catch (Exception e) {
            } 
        }
        txtOldPassword.setEnabled(false);            
        txtNewPassword.setEnabled(false);
        txtAgainNewPassword.setEnabled(false);
        chkChangeMK.setSelected(false);
    }//GEN-LAST:event_btnThayDoiActionPerformed

    private void chkChangeMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkChangeMKActionPerformed
        // TODO add your handling code here:
        if(chkChangeMK.isSelected())
        {
            txtOldPassword.setEnabled(true);            
            txtNewPassword.setEnabled(true);
            txtAgainNewPassword.setEnabled(true);
        }
        else
        {
            txtOldPassword.setEnabled(false);            
            txtNewPassword.setEnabled(false);
            txtAgainNewPassword.setEnabled(false);
        }
    }//GEN-LAST:event_chkChangeMKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEditUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEditUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThayDoi;
    private javax.swing.JCheckBox chkChangeMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAgainNewPassword;
    private javax.swing.JTextField txtNewPassword;
    private javax.swing.JTextField txtOldPassword;
    private javax.swing.JTextField txtTenHT;
    private javax.swing.JTextField txtTenTK;
    // End of variables declaration//GEN-END:variables
}
