/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appcoffee.View;

import appcoffee.Controller.LoaiController;
import appcoffee.Controller.MonController;
import appcoffee.DB_Connect;
import appcoffee.Model.Loai;
import appcoffee.Model.Mon;
import java.lang.reflect.Field;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class frmQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form frmQuanLy
     */
    DB_Connect conn = new DB_Connect("sa", "123", "QLCaPhe");
    MonController dsMon;
    LoaiController dsLoai;
    public frmQuanLy() throws SQLException, ClassNotFoundException {
        initComponents();
//        conn = new DB_Connect("sa", "123", "QLCaPhe");
        pnlXoaSua_Mon.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelDoanhThu = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton21 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        panelMon = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtTen_Mon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLoai_Mon = new javax.swing.JTextField();
        btnTim_Mon = new javax.swing.JButton();
        txtGia_Mon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cboTrangThai_Mon = new javax.swing.JComboBox<>();
        txtTim_Mon = new javax.swing.JTextField();
        chkXoaSua_Mon = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txtMoTa_Mon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlXoaSua_Mon = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtID_Mon = new javax.swing.JTextField();
        pnlTableMon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMon = new javax.swing.JTable();
        btnXem_Mon = new javax.swing.JButton();
        btnThem_Mon = new javax.swing.JButton();
        btnXoa_Mon = new javax.swing.JButton();
        btnSua_Mon = new javax.swing.JButton();
        panelBan = new javax.swing.JPanel();
        btnXem_Ban = new javax.swing.JButton();
        btnThem_Ban = new javax.swing.JButton();
        btnXoa_Ban = new javax.swing.JButton();
        btnSua_Ban = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBan = new javax.swing.JTable();
        txtTim_Ban = new javax.swing.JTextField();
        btnTim_Ban = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTen_Ban = new javax.swing.JTextField();
        txtTrangThai_Ban = new javax.swing.JTextField();
        chkXoaSua_Ban = new javax.swing.JCheckBox();
        pnlXoaSua_Ban = new javax.swing.JPanel();
        txtID_Ban = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        panelLoai = new javax.swing.JPanel();
        panelBan1 = new javax.swing.JPanel();
        btnXem_Loai = new javax.swing.JButton();
        btnThem_Loai = new javax.swing.JButton();
        btnXoa_Loai = new javax.swing.JButton();
        btnSua_Loai = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLoai = new javax.swing.JTable();
        txtTim_Loai = new javax.swing.JTextField();
        btnTim_Loai = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTen_Loai = new javax.swing.JTextField();
        chkXoaSua_Loai = new javax.swing.JCheckBox();
        pnlXoaSua_Loai = new javax.swing.JPanel();
        txtID_Loai = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        panelTaiKhoan = new javax.swing.JPanel();
        panelBan2 = new javax.swing.JPanel();
        btnXem_TaiKhoan = new javax.swing.JButton();
        btnThem_TaiKhoan = new javax.swing.JButton();
        btnXoa_TaiKhoan = new javax.swing.JButton();
        btnSua_TaiKhoan = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTaiKhoan = new javax.swing.JTable();
        txtTim_TaiKhoan = new javax.swing.JTextField();
        btnTim_TaiKhoan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTenDangNhap_TaiKhoan = new javax.swing.JTextField();
        chkXoaSua_TaiKhoan = new javax.swing.JCheckBox();
        pnlXoaSua_TaiKhoan = new javax.swing.JPanel();
        txtID_TaiKhoan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTenHienThi_TaiKhoan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtMatKhau_TaiKhoan = new javax.swing.JTextField();
        txtChucVu_TaiKhoan = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setText("Doanh thu theo Tháng");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton21.setText("Bảng thống kê");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Huy", "Phát", "Tiến", "Quân"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jLabel18.setText("Tổng số lượng");

        jLabel19.setText("Tổng tiền");

        javax.swing.GroupLayout panelDoanhThuLayout = new javax.swing.GroupLayout(panelDoanhThu);
        panelDoanhThu.setLayout(panelDoanhThuLayout);
        panelDoanhThuLayout.setHorizontalGroup(
            panelDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDoanhThuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addGroup(panelDoanhThuLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton21)))
                .addGap(37, 37, 37))
            .addGroup(panelDoanhThuLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        panelDoanhThuLayout.setVerticalGroup(
            panelDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoanhThuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Doanh thu", panelDoanhThu);

        txtTen_Mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTen_MonActionPerformed(evt);
            }
        });

        jLabel4.setText("Mô tả");

        btnTim_Mon.setText("Tìm");

        txtGia_Mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGia_MonActionPerformed(evt);
            }
        });

        jLabel5.setText("Trạng thái");

        txtTim_Mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTim_MonActionPerformed(evt);
            }
        });

        chkXoaSua_Mon.setText("Xóa/Sửa Món");
        chkXoaSua_Mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkXoaSua_MonActionPerformed(evt);
            }
        });

        jLabel3.setText("Giá");

        jLabel2.setText("Loại món");

        jLabel1.setText("Tên món");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboTrangThai_Mon, 0, 217, Short.MAX_VALUE))
                        .addComponent(chkXoaSua_Mon)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtTen_Mon))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLoai_Mon)
                                .addComponent(txtGia_Mon)
                                .addComponent(txtMoTa_Mon))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTim_Mon, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim_Mon)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTim_Mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim_Mon))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTen_Mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtLoai_Mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtGia_Mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtMoTa_Mon, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cboTrangThai_Mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkXoaSua_Mon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlXoaSua_Mon.setBorder(javax.swing.BorderFactory.createTitledBorder("Xóa/Sửa Món"));

        jLabel6.setText("ID Món");

        javax.swing.GroupLayout pnlXoaSua_MonLayout = new javax.swing.GroupLayout(pnlXoaSua_Mon);
        pnlXoaSua_Mon.setLayout(pnlXoaSua_MonLayout);
        pnlXoaSua_MonLayout.setHorizontalGroup(
            pnlXoaSua_MonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXoaSua_MonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtID_Mon)
                .addContainerGap())
        );
        pnlXoaSua_MonLayout.setVerticalGroup(
            pnlXoaSua_MonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXoaSua_MonLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlXoaSua_MonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtID_Mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tblMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quản Lý Món"
            }
        ));
        tblMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMon);

        javax.swing.GroupLayout pnlTableMonLayout = new javax.swing.GroupLayout(pnlTableMon);
        pnlTableMon.setLayout(pnlTableMonLayout);
        pnlTableMonLayout.setHorizontalGroup(
            pnlTableMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableMonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        pnlTableMonLayout.setVerticalGroup(
            pnlTableMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableMonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        btnXem_Mon.setText("Xem");
        btnXem_Mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXem_MonActionPerformed(evt);
            }
        });

        btnThem_Mon.setText("Thêm");
        btnThem_Mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_MonActionPerformed(evt);
            }
        });

        btnXoa_Mon.setText("Xóa");

        btnSua_Mon.setText("Sửa");

        javax.swing.GroupLayout panelMonLayout = new javax.swing.GroupLayout(panelMon);
        panelMon.setLayout(panelMonLayout);
        panelMonLayout.setHorizontalGroup(
            panelMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMonLayout.createSequentialGroup()
                .addGroup(panelMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMonLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnXem_Mon)
                        .addGap(33, 33, 33)
                        .addComponent(btnThem_Mon)
                        .addGap(35, 35, 35)
                        .addComponent(btnXoa_Mon)
                        .addGap(27, 27, 27)
                        .addComponent(btnSua_Mon))
                    .addGroup(panelMonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlTableMon, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlXoaSua_Mon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        panelMonLayout.setVerticalGroup(
            panelMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMonLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXem_Mon)
                    .addComponent(btnThem_Mon)
                    .addComponent(btnXoa_Mon)
                    .addComponent(btnSua_Mon))
                .addGap(18, 18, 18)
                .addGroup(panelMonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMonLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlXoaSua_Mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTableMon, javax.swing.GroupLayout.PREFERRED_SIZE, 427, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Món", panelMon);

        btnXem_Ban.setText("Xem");

        btnThem_Ban.setText("Thêm");

        btnXoa_Ban.setText("Xóa ");

        btnSua_Ban.setText("Sửa");

        tblBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblBan);

        btnTim_Ban.setText("Tìm");

        jLabel7.setText("Tên bàn");

        jLabel8.setText("Trạng thái");

        chkXoaSua_Ban.setText("Xóa/Sửa Bàn");

        pnlXoaSua_Ban.setBorder(javax.swing.BorderFactory.createTitledBorder("Xóa/Sửa Bàn"));

        jLabel9.setText("ID Bàn");

        javax.swing.GroupLayout pnlXoaSua_BanLayout = new javax.swing.GroupLayout(pnlXoaSua_Ban);
        pnlXoaSua_Ban.setLayout(pnlXoaSua_BanLayout);
        pnlXoaSua_BanLayout.setHorizontalGroup(
            pnlXoaSua_BanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXoaSua_BanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(txtID_Ban)
                .addContainerGap())
        );
        pnlXoaSua_BanLayout.setVerticalGroup(
            pnlXoaSua_BanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXoaSua_BanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlXoaSua_BanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtID_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBanLayout = new javax.swing.GroupLayout(panelBan);
        panelBan.setLayout(panelBanLayout);
        panelBanLayout.setHorizontalGroup(
            panelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBanLayout.createSequentialGroup()
                        .addComponent(btnXem_Ban)
                        .addGap(41, 41, 41)
                        .addComponent(btnThem_Ban)
                        .addGap(39, 39, 39)
                        .addComponent(btnXoa_Ban)
                        .addGap(32, 32, 32)
                        .addComponent(btnSua_Ban))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBanLayout.createSequentialGroup()
                        .addComponent(txtTim_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim_Ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(chkXoaSua_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBanLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtTen_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlXoaSua_Ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBanLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTrangThai_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelBanLayout.setVerticalGroup(
            panelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBanLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXem_Ban)
                    .addComponent(btnThem_Ban)
                    .addComponent(btnXoa_Ban)
                    .addComponent(btnSua_Ban))
                .addGap(18, 18, 18)
                .addGroup(panelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBanLayout.createSequentialGroup()
                        .addGroup(panelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTim_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTim_Ban))
                        .addGap(28, 28, 28)
                        .addGroup(panelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTen_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panelBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTrangThai_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(chkXoaSua_Ban)
                        .addGap(18, 18, 18)
                        .addComponent(pnlXoaSua_Ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Bàn", panelBan);

        btnXem_Loai.setText("Xem");

        btnThem_Loai.setText("Thêm");

        btnXoa_Loai.setText("Xóa ");

        btnSua_Loai.setText("Sửa");

        tblLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblLoai);

        btnTim_Loai.setText("Tìm");

        jLabel10.setText("Tên loại");

        chkXoaSua_Loai.setText("Xóa/Sửa Loại");
        chkXoaSua_Loai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkXoaSua_LoaiActionPerformed(evt);
            }
        });

        pnlXoaSua_Loai.setBorder(javax.swing.BorderFactory.createTitledBorder("Xóa/Sửa Loại"));

        jLabel12.setText("ID Loại");

        javax.swing.GroupLayout pnlXoaSua_LoaiLayout = new javax.swing.GroupLayout(pnlXoaSua_Loai);
        pnlXoaSua_Loai.setLayout(pnlXoaSua_LoaiLayout);
        pnlXoaSua_LoaiLayout.setHorizontalGroup(
            pnlXoaSua_LoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXoaSua_LoaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtID_Loai)
                .addContainerGap())
        );
        pnlXoaSua_LoaiLayout.setVerticalGroup(
            pnlXoaSua_LoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXoaSua_LoaiLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlXoaSua_LoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtID_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBan1Layout = new javax.swing.GroupLayout(panelBan1);
        panelBan1.setLayout(panelBan1Layout);
        panelBan1Layout.setHorizontalGroup(
            panelBan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBan1Layout.createSequentialGroup()
                        .addComponent(btnXem_Loai)
                        .addGap(41, 41, 41)
                        .addComponent(btnThem_Loai)
                        .addGap(39, 39, 39)
                        .addComponent(btnXoa_Loai)
                        .addGap(32, 32, 32)
                        .addComponent(btnSua_Loai))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBan1Layout.createSequentialGroup()
                        .addComponent(txtTim_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim_Loai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(chkXoaSua_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBan1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtTen_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlXoaSua_Loai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelBan1Layout.setVerticalGroup(
            panelBan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBan1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelBan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXem_Loai)
                    .addComponent(btnThem_Loai)
                    .addComponent(btnXoa_Loai)
                    .addComponent(btnSua_Loai))
                .addGap(18, 18, 18)
                .addGroup(panelBan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBan1Layout.createSequentialGroup()
                        .addGroup(panelBan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTim_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTim_Loai))
                        .addGap(28, 28, 28)
                        .addGroup(panelBan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTen_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(chkXoaSua_Loai)
                        .addGap(18, 18, 18)
                        .addComponent(pnlXoaSua_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelLoaiLayout = new javax.swing.GroupLayout(panelLoai);
        panelLoai.setLayout(panelLoaiLayout);
        panelLoaiLayout.setHorizontalGroup(
            panelLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
            .addGroup(panelLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLoaiLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelBan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelLoaiLayout.setVerticalGroup(
            panelLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(panelLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLoaiLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelBan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Loại", panelLoai);

        btnXem_TaiKhoan.setText("Xem");

        btnThem_TaiKhoan.setText("Thêm");

        btnXoa_TaiKhoan.setText("Xóa ");

        btnSua_TaiKhoan.setText("Sửa");

        tblTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblTaiKhoan);

        btnTim_TaiKhoan.setText("Tìm");

        jLabel11.setText("Tên đăng nhập");

        chkXoaSua_TaiKhoan.setText("Xóa/Sửa Tài Khoản");
        chkXoaSua_TaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkXoaSua_TaiKhoanActionPerformed(evt);
            }
        });

        pnlXoaSua_TaiKhoan.setBorder(javax.swing.BorderFactory.createTitledBorder("Xóa/Sửa Tài Khoản"));

        jLabel13.setText("ID Tài Khoản");

        javax.swing.GroupLayout pnlXoaSua_TaiKhoanLayout = new javax.swing.GroupLayout(pnlXoaSua_TaiKhoan);
        pnlXoaSua_TaiKhoan.setLayout(pnlXoaSua_TaiKhoanLayout);
        pnlXoaSua_TaiKhoanLayout.setHorizontalGroup(
            pnlXoaSua_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXoaSua_TaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID_TaiKhoan)
                .addContainerGap())
        );
        pnlXoaSua_TaiKhoanLayout.setVerticalGroup(
            pnlXoaSua_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlXoaSua_TaiKhoanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlXoaSua_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtID_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel14.setText("Tên hiển thị");

        jLabel15.setText("Mật khẩu");

        jLabel16.setText("Chức vụ");

        javax.swing.GroupLayout panelBan2Layout = new javax.swing.GroupLayout(panelBan2);
        panelBan2.setLayout(panelBan2Layout);
        panelBan2Layout.setHorizontalGroup(
            panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBan2Layout.createSequentialGroup()
                        .addComponent(btnXem_TaiKhoan)
                        .addGap(41, 41, 41)
                        .addComponent(btnThem_TaiKhoan)
                        .addGap(39, 39, 39)
                        .addComponent(btnXoa_TaiKhoan)
                        .addGap(32, 32, 32)
                        .addComponent(btnSua_TaiKhoan))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBan2Layout.createSequentialGroup()
                        .addComponent(txtTim_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                    .addGroup(panelBan2Layout.createSequentialGroup()
                        .addGroup(panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelBan2Layout.createSequentialGroup()
                                    .addGroup(panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel14))
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBan2Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(47, 47, 47)))
                            .addGroup(panelBan2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(53, 53, 53)))
                        .addGroup(panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenDangNhap_TaiKhoan)
                            .addComponent(txtTenHienThi_TaiKhoan)
                            .addComponent(txtMatKhau_TaiKhoan)
                            .addComponent(txtChucVu_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                    .addComponent(pnlXoaSua_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkXoaSua_TaiKhoan))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        panelBan2Layout.setVerticalGroup(
            panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBan2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXem_TaiKhoan)
                    .addComponent(btnThem_TaiKhoan)
                    .addComponent(btnXoa_TaiKhoan)
                    .addComponent(btnSua_TaiKhoan))
                .addGap(18, 18, 18)
                .addGroup(panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBan2Layout.createSequentialGroup()
                        .addGroup(panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTim_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTim_TaiKhoan))
                        .addGap(28, 28, 28)
                        .addGroup(panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTenDangNhap_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtTenHienThi_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtMatKhau_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelBan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtChucVu_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(chkXoaSua_TaiKhoan)
                        .addGap(18, 18, 18)
                        .addComponent(pnlXoaSua_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTaiKhoanLayout = new javax.swing.GroupLayout(panelTaiKhoan);
        panelTaiKhoan.setLayout(panelTaiKhoanLayout);
        panelTaiKhoanLayout.setHorizontalGroup(
            panelTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
            .addGroup(panelTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTaiKhoanLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelBan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );
        panelTaiKhoanLayout.setVerticalGroup(
            panelTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(panelTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTaiKhoanLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelBan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Tài khoản", panelTaiKhoan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Function for Loai
//    private void readData_Loai() throws SQLException {
//        String sql = "select * from Loai";
//        ResultSet rs = conn.getReader(sql);
//        while(rs.next()) {
//            int idLoai = Integer.parseInt(rs.getString("idLoai"));
//            String ten = String.valueOf(rs.getString("tenLoai"));
//            Loai loai = new Loai(idLoai, ten);
//            dsLoai.themLoai(loai);
//        }
//    }
    
    private void load_CBOTrangThai() throws SQLException {
//        DefaultComboBoxModel<TrangThai_Mon> cboTrangThai = (DefaultComboBoxModel)cboTrangThai_Mon.getModel();
//        readData_Loai();
//        for(Loai loai : dsLoai.dsLoai) {
//            cboLoai.addElement(loai);
//        }
    }
    //Function for Mon
    
    private String[] getColumn_Data(Object ob) throws SQLException {
        // Lấy thông tin về số cột và tên cột của ResultSet
        Field[] fields = ob.getClass().getDeclaredFields();
        String[] columnNames = new String[fields.length];
        // Lặp qua danh sách các trường và lấy tên của từng trường
        for (int i = 0; i < fields.length; i++) {
            columnNames[i] = fields[i].getName();
        }
        return columnNames;
    }
    
    private void themMon(int idMon, String tenMon, int idLoai, int gia, String moTa, int trangThai) throws SQLException {
        String sql = "insert into Mon(idMon, tenMon, idLoai, gia, moTa, trangThai) values " +
                "(" + idMon + ", N'" + tenMon + "', " + idLoai + ", " + gia + ", " + "N'" + moTa + "', " + trangThai + ")";
        conn.GetNonQuery(sql);
    }
    
    
    
    private void xemMon() {
        // TODO add your handling code here:
        try {
            DefaultTableModel tblModel = (DefaultTableModel)tblMon.getModel();
            ArrayList<Mon> ds = MonController.init(conn);
            Mon a = new Mon();
            String[] columnNames = getColumn_Data(a);
            tblModel.setColumnIdentifiers(columnNames);
            for(Mon mon : ds) {
                Object[] rowData = {mon.getIdMon(), mon.getTen(), mon.getIdLoai(), mon.getGia(), mon.getMoTa(), mon.getTrangThai()};
                tblModel.addRow(rowData);
            }
            dsMon = new MonController(ds);
        } catch (SQLException ex) {
            Logger.getLogger(frmQuanLy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void chkXoaSua_LoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkXoaSua_LoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkXoaSua_LoaiActionPerformed

    private void chkXoaSua_TaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkXoaSua_TaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkXoaSua_TaiKhoanActionPerformed

    private void btnXem_MonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXem_MonActionPerformed
//        try {
//            conn = new DB_Connect("sa", "123", "QLCaPhe");
//            xemMon(conn);
//        } catch (SQLException ex) {
//            Logger.getLogger(frmQuanLy.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(frmQuanLy.class.getName()).log(Level.SEVERE, null, ex);
//        }
        xemMon();
    }//GEN-LAST:event_btnXem_MonActionPerformed

    private void chkXoaSua_MonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkXoaSua_MonActionPerformed
        // TODO add your handling code here:
        if(chkXoaSua_Mon.isSelected()) {
            pnlXoaSua_Mon.setVisible(true);
        }
        else {
            pnlXoaSua_Mon.setVisible(false);
        }
    }//GEN-LAST:event_chkXoaSua_MonActionPerformed

    private void btnThem_MonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_MonActionPerformed
        // TODO add your handling code here:
//        int idMon = Integer.parseInt(txtID_Mon.getText());
//        String tenMon = txtTen_Mon.getText().toString();
//        Loai selected = (Loai)cboTrangThai_Mon.getSelectedItem();
//        int idLoai = selected.getIdLoai();
//        int gia = Integer.parseInt(txtGia_Mon.getText());
//        String moTa = txtMoTa_Mon.getText().toString();
//        int trangThai = 
    }//GEN-LAST:event_btnThem_MonActionPerformed

    private void txtTen_MonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTen_MonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTen_MonActionPerformed

    private void txtGia_MonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGia_MonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGia_MonActionPerformed

    private void txtTim_MonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTim_MonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTim_MonActionPerformed

    private void tblMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonMouseClicked
        // TODO add your handling code here:
        int row = tblMon.getSelectedRow();
        txtID_Mon.setText(String.valueOf(tblMon.getValueAt(row, 0)));
        txtTen_Mon.setText(String.valueOf(tblMon.getValueAt(row, 1)));
        txtLoai_Mon.setText(String.valueOf(tblMon.getValueAt(row, 2)));
        txtGia_Mon.setText(String.valueOf(tblMon.getValueAt(row, 3)));
        txtMoTa_Mon.setText(String.valueOf(tblMon.getValueAt(row, 4)));
    }//GEN-LAST:event_tblMonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmQuanLy().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmQuanLy.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(frmQuanLy.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua_Ban;
    private javax.swing.JButton btnSua_Loai;
    private javax.swing.JButton btnSua_Mon;
    private javax.swing.JButton btnSua_TaiKhoan;
    private javax.swing.JButton btnThem_Ban;
    private javax.swing.JButton btnThem_Loai;
    private javax.swing.JButton btnThem_Mon;
    private javax.swing.JButton btnThem_TaiKhoan;
    private javax.swing.JButton btnTim_Ban;
    private javax.swing.JButton btnTim_Loai;
    private javax.swing.JButton btnTim_Mon;
    private javax.swing.JButton btnTim_TaiKhoan;
    private javax.swing.JButton btnXem_Ban;
    private javax.swing.JButton btnXem_Loai;
    private javax.swing.JButton btnXem_Mon;
    private javax.swing.JButton btnXem_TaiKhoan;
    private javax.swing.JButton btnXoa_Ban;
    private javax.swing.JButton btnXoa_Loai;
    private javax.swing.JButton btnXoa_Mon;
    private javax.swing.JButton btnXoa_TaiKhoan;
    private javax.swing.JComboBox<String> cboTrangThai_Mon;
    private javax.swing.JCheckBox chkXoaSua_Ban;
    private javax.swing.JCheckBox chkXoaSua_Loai;
    private javax.swing.JCheckBox chkXoaSua_Mon;
    private javax.swing.JCheckBox chkXoaSua_TaiKhoan;
    private javax.swing.JButton jButton21;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JPanel panelBan;
    private javax.swing.JPanel panelBan1;
    private javax.swing.JPanel panelBan2;
    private javax.swing.JPanel panelDoanhThu;
    private javax.swing.JPanel panelLoai;
    private javax.swing.JPanel panelMon;
    private javax.swing.JPanel panelTaiKhoan;
    private javax.swing.JPanel pnlTableMon;
    private javax.swing.JPanel pnlXoaSua_Ban;
    private javax.swing.JPanel pnlXoaSua_Loai;
    private javax.swing.JPanel pnlXoaSua_Mon;
    private javax.swing.JPanel pnlXoaSua_TaiKhoan;
    private javax.swing.JTable tblBan;
    private javax.swing.JTable tblLoai;
    private javax.swing.JTable tblMon;
    private javax.swing.JTable tblTaiKhoan;
    private javax.swing.JTextField txtChucVu_TaiKhoan;
    private javax.swing.JTextField txtGia_Mon;
    private javax.swing.JTextField txtID_Ban;
    private javax.swing.JTextField txtID_Loai;
    private javax.swing.JTextField txtID_Mon;
    private javax.swing.JTextField txtID_TaiKhoan;
    private javax.swing.JTextField txtLoai_Mon;
    private javax.swing.JTextField txtMatKhau_TaiKhoan;
    private javax.swing.JTextField txtMoTa_Mon;
    private javax.swing.JTextField txtTenDangNhap_TaiKhoan;
    private javax.swing.JTextField txtTenHienThi_TaiKhoan;
    private javax.swing.JTextField txtTen_Ban;
    private javax.swing.JTextField txtTen_Loai;
    private javax.swing.JTextField txtTen_Mon;
    private javax.swing.JTextField txtTim_Ban;
    private javax.swing.JTextField txtTim_Loai;
    private javax.swing.JTextField txtTim_Mon;
    private javax.swing.JTextField txtTim_TaiKhoan;
    private javax.swing.JTextField txtTrangThai_Ban;
    // End of variables declaration//GEN-END:variables
}
